hrgdavor/jscadui

- README.md
- apps/engine-test/README.md
- apps/engine-test/main.js
- apps/engine-test/static/index.html
- apps/engine-test/static/main.css
- packages/fs-provider/README.md
- packages/worker/worker.js
This PR adds a try-catch around model generation in the worker. Any error thrown will be emitted as an "error" event using `client.sendNotify`.
I added a simple overlay div to the `engine-test` app to display model errors:
I also fixed some typos in the READMEs, sorry I couldn't help myself :laughing: 
Let me know what you think, or if you had a different idea for how to handle exceptions.
> feat(worker): emit error event

- apps/jscad-web/main.js
- apps/jscad-web/src/editor.js
- apps/jscad-web/static/index.html
- apps/jscad-web/static/main.css
- packages/html-gizmo/index.js
Features:
- Ctrl-S to update model (apple-S on mac)
- Strip double "Error: " messages
- Show spinner while generating geometry
Fix:
- Gizmo use pointer-events instead of mouse-events to fix hover on mobile
> Updates to jscad-web

- apps/engine-test/main.js
- apps/jscad-web/main.js
- apps/jscad-web/src/editor.js
- apps/jscad-web/static/main.css
- packages/format-jscad/index.js
- packages/format-threejs/index.js
- packages/render-threejs/index.js
- packages/require/src/readFileWeb.js
- packages/require/src/require.js
- packages/worker/worker.js
This PR contains fixes to several packages:
- handle errors thrown in `runScript`. this can happen when imports are not found.
- handle errors in `require`. this can happen for missing npm packages.
- fix relative path resolution. now I can drop multi-file projects and they work! this one took a lot of testing to get right.
- handle invalid geometries. this one I noticed when I accidentally returned a function instead of jscad objects.
- fix auto-reload for dependent files. previously it wasn't updating, due to cache key mismatch.
Basically I made a bunch of test files with: empty file, missing exports, various invalid imports, relative imports, nested folders, and anything silly I could think of. Fixed a ton of bugs, the loader code should be pretty robust now.
> fix: module loading, and lots of error handling

- apps/engine-test/main.js
- apps/jscad-web/main.js
- packages/fs-provider/fs-provider.js
- packages/postmessage/README.md
- packages/postmessage/index.js
- packages/worker/worker.js
Add `sendError` method to `postmessage` to return errors thrown back to the caller.
This makes it so that any error thrown in a `postmessage` command will be automatically returned to the caller as part of the promise. This makes error handling more simple, and more likely to catch unforeseen errors. I was able to remove some `try` clauses, because the errors will be caught and sent back to the main thread automatically now.
I did this work as I was trying to track down a bug where sometimes `/swfs/init` returns 404, resulting in `sw.id` not being set correctly. This commit does not actually fix the service worker issue, but at least raises the error to the user when it happens:
> fix: send service worker errors back to caller

- file-format/3mf-export/index.js
- file-format/3mf-export/src/pushObjectComponent.js
- file-format/3mf-export/src/pushObjectMesh.js
Since I'm introducing a couple of breaking API changes anyway, I took the liberty of renaming a few things to reduce confusion (hopefully). `transforms -> transform` (since there's only one), `items -> children` since there is now a dedicated input called `items` which correspond to 3MF items. These allow one to define the roots of the component trees (before, the branches were all getting duplicated). I also added an optional precision parameter - it cut the file size by ~30% setting it to 7 instead of the default (since manifold uses float precision). I doubt there are many 3D printers that can really make use of double precision...
I've tested this in ManifoldCAD.org with corresponding changes to export our scene hierarchy and it's working well. My auto-format doesn't match the code …
> fixed 3mf hierarchy export

- apps/jscad-web/examples/hulls.example.js
- apps/jscad-web/examples/slicer.example.js
- apps/jscad-web/src/drawer.js
- apps/jscad-web/src/editor.js
- apps/jscad-web/src/examples.js
- apps/jscad-web/static/index.html
- apps/jscad-web/static/main.css
Simple change, move code for the "resizeable drawer panel" out of `editor.js` and into its own `drawer.js` file.
Also includes minor changes:
- set minimum width on the viewer so that you can't lose the resize toggle
- code style of the hull example
- remove unused `setCompileFun`
- add GitHub link to welcome screen
- add slicer example
> refactor: split out resizable drawer

- apps/jscad-web/examples/slicer.example.js
- apps/jscad-web/src/examples.js
- apps/jscad-web/static/main.css
- packages/format-jscad/index.js
This PR adds support for new JSCAD v3 geometry data structures being returned.
The changes in JSCAD v3 include:
- `geom2` changed from using `sides` to `outlines`
- `slice` is a first-class geometry now, and changed from `edges` to `contours`
Procedure for using JSCADUI with JSCAD v3 locally:
```bash
cd ~/jscad/packages/modeling
git checkout V3
npm link
cd ~/jscadui/apps/jscad-web
npm link @jscad/modeling
rm -rf build_dev
npm start
```
Very exciting!!
> format-jscad: support for V3 geometry data structures

- apps/jscad-web/build.js
- apps/jscad-web/main.js
- apps/jscad-web/package.json
- apps/jscad-web/serve.js
- apps/jscad-web/src/remote.js
- apps/jscad-web/src/welcome.js
This PR adds a minimal web server using the built in node `http` package (who needs dependencies anyway?)
It can be run with `npm run serve`
It also adds the neat feature from JSCAD v2 where you can load a script by url like:
https://jscad.app/#https://raw.githubusercontent.com/gilboonet/designs/master/2023/demo_creeMeuble2.js
(@gilboonet)
This required the following changes:
- add `serve.js` which starts a minimal http server
- handle serving static files from the `build` dir
- handle `index.html` as default file
- handle `/remote` endpoint which proxies fetch requests to cross domain urls
- handle `/docs` redirect to `/docs/`
- handle missing files, urls, etc
- handle mimetype detection
- server request logging
- client side checking for `#url` in location …
> jscad-web: http server

- .gitignore
- apps/jscad-web/main.js
- packages/fs-provider/README.md
- packages/fs-provider/fs-provider.js
Was having issue with service worker on jscad.app, so I did some debugging. I think this should now properly handle all the cases:
- normal browser (with and without sw loaded already)
- private browser
- hard refresh ctrl-shift-r (service worker initially disabled by browser, so reload)
Note: I now call `initFs` at startup. Previously this would only happen on file drop, but that led to bad user experience where: after a hard refresh, user drops file, page reloads but user has no indication of why dropping their file didn't work, and that they need to drop it again. By moving `initFs` to page load, it will refresh if needed BEFORE the user drops anything.
> fix: service worker init

- apps/jscad-web/examples/hulls.example.js
- apps/jscad-web/main.js
- apps/jscad-web/serve.js
- apps/jscad-web/src/welcome.js
- apps/jscad-web/static/robots.txt
1. there was an issue where if you either load a model via remote url, or if you're quick about drag-and-dropping a file, the default model will load AFTER it, and replace the content. This PR fixes that by disabling default model loading once any other model has been loaded
2. add `robots.txt` file (allow all)
3. cleanup the `serve.js` code style
4. tweak hull example to show how it can be used to make a shape that **isn't** just a rounded rectangle
5. easter egg: add a greeting message to any users who open the dev console. `Welcome to JSCAD! Like JavaScript and want to help? Join us at https://github.com/jscad/OpenJSCAD.org`
> jscad-web: fix default model

- apps/jscad-web/main.js
- apps/jscad-web/src/stacktrace.js
- apps/jscad-web/static/main.css
- packages/postmessage/index.js
This PR adds stacktrace support to jscad.app
Previously this would have just given `error.toString()` but now it gives a full stacktrace.
Changes:
- Add `formatStacktrace` function which parses a stacktrace and extracts the lines which were inside the `eval` function.
- Remove noise from stacktrace introduced by `eval`
- Serialize `stack` specifically in `postmessage` because otherwise it gets lost in transit (necessary for firefox)
> Extract stacktrace from eval

- apps/engine-test/main.js
- apps/jscad-web/main.js
- packages/fs-provider/fs-provider.js
- packages/postmessage/index.js
- packages/require/src/readFileWeb.js
- packages/require/src/require.js
- packages/require/src/resolveUrl.js
- packages/require/test/resolveUrl.test.js
- packages/require/test/workspace.import.test.js
- packages/require/test/workspace.import2level.test.js
- packages/worker/worker.js
Very small PR that fixes two issues:
1. Fix `clearCache` function which was doing nothing, due to misuse of `Cache.keys()` function.
2. Fix regression on relative imports.  For example, import `./brother.js` from `src/sister.js` was missing `src` from base path, and so it would look in the top level directory instead of the `src` folder. This worked previously but was regressed by #51.
`index.js`:
```js
const bro = require('./src/brother.js')
```
`src/brother.js`:
```js
const sis = require('./sister.js')
```
`src/sister.js`:
```js
module.exports = { main: () => [] }
```
> Fix require edge cases

- apps/cardboard-cutter/README.md
- apps/cardboard-cutter/index.html
- apps/cardboard-cutter/main.js
- apps/jscad-examples/README.md
- apps/jscad-examples/examples/core/extrusions/nutsAndBolts.js
- apps/jscad-examples/examples/index.js
- apps/jscad-examples/index.html
- apps/jscad-examples/main.js
- apps/jscad-web/README.md
- apps/model-page/README.md
- apps/model-page/index.html
- apps/model-page/main.js
- apps/model-page/package.json
As we've been evolving the jscadui project with a focus on jscad.app... some of the other apps got broken along the way. Users are still asking about how to host standalone model pages, so it would be good to keep them working.
Most of the breakage was from changing `runFile` to `runScript`.
I also took the liberty of updating the `jscad-examples` app with a new design... it is a parameterized dropdown that let's you select from the other examples.
I also updated the READMEs, mostly fixing typos and adding some more details.
> fix other apps

- apps/jscad-web/main.js
- apps/jscad-web/serve.js
- apps/jscad-web/src/remote.js
- apps/jscad-web/src/welcome.js
When loading a remote url via link, try to fetch url directly first. Only use the serverside `/remote` endpoint as a fallback to workaround cors when needed.
This makes it easier to test things while running in dev mode, reduces server load, and improves user privacy.
Also fixed small bug where error on url load would disappear when default model loads, and added content type for robots.txt.
> jscad-web: try to fetch script directly first

- apps/jscad-web/main.js
- apps/jscad-web/src/drawer.js
- apps/jscad-web/src/editor.js
- apps/jscad-web/src/remote.js
- apps/jscad-web/static/index.html
- apps/jscad-web/static/main.css
This PR was focused on making it so that the resizable editor behavior is optimal.
- change from `mouseup` to `pointerup` etc. so that mobile can drag to resize
- save the open/closed state separately from the width
- if user resizes to less than 10 pixels, snap closed
- restore open/closed and width in index.html to prevent re-layouts
- make "shift-enter to update" hint clickable
- fix remote proxy code from the last PR
> jscad-web: resizable drawer fixes

- apps/jscad-web/main.js
- apps/jscad-web/src/editor.js
- apps/jscad-web/src/engine.js
- apps/jscad-web/src/exporter.js
- apps/jscad-web/src/menu.js
- apps/jscad-web/src/remote.js
- apps/jscad-web/src/stacktrace.js
- apps/jscad-web/src/welcome.js
- apps/jscad-web/static/index.html
- packages/fs-provider/fs-provider.js
- packages/require/src/require.js
This PR updates some of the error handling to give nicer error messages in the error bar. It shows the error name in bold up front, and preserves stacktraces a little better.
Before:
After:
I also fixed a bug where generating a bunch of designs in a row (such as by changing parameters), the progress spinner would disappear after the first job even though jobs are still pending. I changed this to track the number of pending jobs and only hide the spinner when there are no pending jobs.
I also fixed some code style issues from prettier, mostly single quote strings.
> jscad-web: show error name

- apps/jscad-web/src_bundle/bundle.worker.js
- packages/require/src/readFileWeb.js
- packages/require/src/require.js
- packages/worker/worker.js
I hacked up a quick support to require stl and other jscad supported geometry.
it may not work for all that work on jscad web, but it definitely works for openjscad examples https://github.com/jscad/OpenJSCAD.org/tree/master/packages/examples/import
AMFImport
STLImport
SVGImport
> require-geometry-files

- apps/jscad-web/src_bundle/bundle.worker.js
- apps/jscad-web/static/test.file.js
- packages/fs-provider/fs-provider.js
- packages/require/src/require.js
- packages/worker/worker.js
file imput supprot for parameters, that reads file the same ways as require for different types of geometry.
example script:
```js
import * as jscad from '@jscad/modeling'
export const main =({// @jscad-params
mesh,// {type:"file"}
check=false,
})=>{  
return mesh ? mesh : jscad.primitives.sphere()
}
```
no file chosen, the sample script returns a sphere
stl file, the sample script returns the geometry form the stl
> feat-file-input

- apps/jscad-web/static/main.css
Makes the "choice" parameter style consistent with other parameter types.
Thanks @eevleevs for raising this [issue](https://github.com/jscad/OpenJSCAD.org/issues/1314)
I also made adjusted the welcome screen style so that it won't overflow the screen in mobile landscape mode.
> minor style fixes

- apps/jscad-web/examples/multipart.project.template.js
- apps/jscad-web/src/examples.js
An example I shared on jscad that I think is useful. I use this template for some projects
https://github.com/jscad/OpenJSCAD.org/discussions/1141
it is a nice way for multiple parts to share the same parameter values without needing to declare them in each function.
> multipart-project-example

- apps/jscad-web/static/index.html
fixes: #55
This PR intends to give users link to jscadui repo along with link to JSCAD issues.
Question is if we can make it clearer which issues are for the jscad.app and which for jscad
bit of text with links on splash screen
> improve-github-issues

- apps/jscad-web/package.json
- apps/jscad-web/src/remote.js
- package-lock.json
fixes: #76
here is a sample gzipped script:
`data:application/gzip;base64,H4sICN1FqGUAA3Rlc3QADcrBDkAwDADQu6/YjV3GxUUi8SuLFRXrpl1FIv6dd34xBT3AwZ0TFxkXpblgIhM9UmMfhqJMhuFUZGjqaZfZhzamAAfSWluXGSMWvECc5A3+9LAPqDKYvnvtW33S8ZutYgAAAA==`
for script:
```js
module.exports=function main(){return require('@jscad/modeling').primitives.sphere({radius: 50})}
```
@Hermann-SW  works temporarily here(you may need to hit ctrl+F5) until merged and published to jscad.app
https://3d.hrg.hr/jscad/app1/#data:application/gzip;base64,H4sICN1FqGUAA3Rlc3QADcrBDkAwDADQu6/YjV3GxUUi8SuLFRXrpl1FIv6dd34xBT3AwZ0TFxkXpblgIhM9UmMfhqJMhuFUZGjqaZfZhzamAAfSWluXGSMWvECc5A3+9LAPqDKYvnvtW33S8ZutYgAAAA==
> gzip in data: uri

- apps/jscad-web/examples/balloons.example.js
- apps/jscad-web/examples/extrusions.example.js
- apps/jscad-web/examples/gear.example.js
- apps/jscad-web/examples/hulls.example.js
- apps/jscad-web/examples/jscad.example.js
- apps/jscad-web/examples/multipart.project.template.js
- apps/jscad-web/examples/nuts-and-bolts.example.js
- apps/jscad-web/examples/parameters.example.js
- apps/jscad-web/examples/primitives.example.js
- apps/jscad-web/examples/slicer.example.js
- apps/jscad-web/examples/text.example.js
Fixes #82 
@Hermann-SW raised a good point: right now the scripts used as examples ONLY work on jscad.app because of the magic of jscadui's import handling. This is especially confusing as we are in transition from V2 with `require` and V3 with ES module `import`.
To be consistent, in this PR I reverted the example scripts to use V2 `require` syntax, which should work in both openjscad.xyz and jscad.app.
At some point, once JSCAD V3 is released, I think we should update the examples to use `import` statements, along with the new "flattened" V3 api. But not yet.
> Convert examples to use JSCAD v2 syntax

- apps/jscad-web/main.js
- apps/jscad-web/src/viewState.js
- apps/jscad-web/static/index.html
- packages/format-threejs/index.js
- packages/render-threejs/index.js
demo https://3d.hrg.hr/jscad/smooth/
OLD
NEW
dark mode
checkbox menu item is disabled by default
> Lighting like other cad software

- .gitignore
- apps/jscad-web/main.js
- apps/jscad-web/src/editor.js
- packages/fs-provider/fs-provider.js
- packages/fs-provider/src/FileEntry.js
- packages/require/src/require.js
demo: https://3d.hrg.hr/jscad/save/
like mentioned in https://github.com/hrgdavor/jscadui/issues/88#issuecomment-1906776094
feature  to allow `ctrl+s` to save file from editors
basic flow is initally implemented for solo script in the editor, 
more to do
not caused here
https://github.com/hrgdavor/jscadui/assets/2480762/31bc8ea9-180d-488f-8c57-694bc8588156
> feature-save-file

- apps/jscad-web/static/main.css
- apps/vue3-jscad/src/App.vue
Closed parameter group used a larger triangle shape
> Adjust parameter triangle size and position

- apps/jscad-web/main.js
- packages/fs-provider/fs-provider.js
- packages/fs-serviceworker/fs-serviceworker.js
- packages/postmessage/index.js
Two cases here:
* app first load: the script try to fetch on 'swfs/init' to get the clientId but without waiting to be sure that the SW is fully activated (ie. `serviceWorker.state = 'activated'`).
* hard refresh: when calling for a hard refresh the browser behavior is to remove the page from the SW control, so `navigator.serviceWorker.controller` is `null`. The page has to call the SW and ask him to claim the page.
Both issue are fixed by this issue.
> Fixing SW: first time and hard refreshing

- apps/jscad-web/static/main.css
- packages/params-form/src/params.js
Fixing bumpy ranges and sliders on issue #111 
I encapsulated the  i tag inside an inline-block span with a larger width, and then right-align the i, to keep the same look as the initial one, just without the bump.
> Fixing issue #111 on bumpy slider

- apps/jscad-web/examples/AMFImport/index.js
- apps/jscad-web/examples/STLImport/index.js
- apps/jscad-web/examples/SVGImport/index.js
- apps/jscad-web/examples/balloons.example.js
- apps/jscad-web/examples/extrusions.example.js
- apps/jscad-web/examples/gear.example.js
- apps/jscad-web/examples/hulls.example.js
- apps/jscad-web/examples/jscad.example.js
- apps/jscad-web/examples/multipart.project.template.js
- apps/jscad-web/examples/nuts-and-bolts.example.js
- apps/jscad-web/examples/parameters.example.js
- apps/jscad-web/examples/primitives.example.js
- apps/jscad-web/examples/slicer.example.js
- apps/jscad-web/examples/svg.tester.js
- apps/jscad-web/examples/text.example.js
As discussed on discord.
Only
```
"use strict"
```
without semicolon as many don't like semicolon on discord
> Prepend "use strict" to all 15 examples

- apps/engine-test/main.js
- apps/jscad-web/main.js
- packages/fs-provider/fs-provider.js
- packages/require/src/require.js
- packages/worker/worker.js
This changes do several things:
1. Fix the cache clearing after modifications in imported files. The fs-provider uses the file path. The cache uses the URL. I have added some logic to generate the URL from the path. This URL can then be used to clear the cache.
2. Implement logic for clearing the cache in indirectly imported files. The new Map requireCache.knownDependencies contains a list of all files that are imported for a specific file. This information is used to recursively clear the caches of other modules when one of its dependencies has changed.
3. Add more JSDoc Type annotations
4. Some minor syntax cleanups (let => const, || => ??, self=>globalThis, ...)
This updates for changes in the main file are still broken due to a bug in a prior commit.
> Allow reload after changes in imported files
